In [4]:
#--------------------Trembling hand graphs--------------------#

print('Running Trembling Hand')
import numpy as np
import pandas as pd

# Parameters
vh = 200
vl = 100
ph = 160
pl =  80
ch =  40
cl =   0

m1 = (ph - vl) / (vh - vl)
m2 = (ph - pl) / (vh - vl)
kl  = (pl - cl) / (ph - cl)
kh  = (pl - ch) / (ph - ch)
x1  = 1 / (2 * m1)
x2  = 1 / (2 * m2)
x3  = 1 - x2

cln_data_path = '../output/Data Background/'
bysess_all_1s = pd.read_excel(cln_data_path + 'bysess_all_1s_first.xlsx')
bysess_all_2s = pd.read_excel(cln_data_path + 'bysess_all_2s_first.xlsx')

data_1s = bysess_all_1s[['pbhh', 'pbdh', 'pbll', 'pbdl', 
                        'pshh', 'pslh', 'pshl', 'psll']].values
data_2s = bysess_all_2s[['pbhh', 'pbdh', 'pbll', 'pbdl', 'pbhb', 'pblb', 'pbdb', 
                        'pshh', 'pslh', 'pshl', 'psll']].values

#--------------------n = 1: choice probs on e--------------------#

e = np.array([1, 2/3, 2/3, 0])
pbll = 1 - e / 2
pbhh = np.array([1/2, 1/3, 1/3, 1/2])
pshh = 1 - e / 2
pshl = np.array([1/2, 2/3, 4/9, 2/3])
pbdh = 1 - pbhh
pbdl = 1 - pbll
pslh = 1 - pshh
psll = 1 - pshl

dicty = {'pbhh': pbhh, 'pbdh': pbdh, 'pbll': pbll, 'pbdl': pbdl, 'pshh': pshh, 'pslh': pslh, 'pshl': pshl, 'psll': psll, 'e': e}
dfmain1 = pd.DataFrame(dicty)
dfmain1['muh'] = dfmain1['pshh'] / (dfmain1['pshh'] + dfmain1['pshl'])
dfmain1['mul'] = (1 - dfmain1['pshh']) / (2 - dfmain1['pshh'] - dfmain1['pshl'])

# Just for graphing
dfmain1['e'] = 1 - dfmain1['e']
dfmain1['pshl'] = dfmain1['pshl'] - 0.01
dfmain1['mul'] = dfmain1['mul'] - 0.01

e = np.array([0.00001, 1/2, 1/2, 0.00001])
pbll = 1 - e / 2
pbhh = np.array([0.00001, 1/4, 1/4, 1/3])
pshh = np.array([0.00001, 1/4, 3/8, 0.00001])
pshl = e / 2
pbdh = 1 - pbhh
pbdl = 1 - pbll
pslh = 1 - pshh
psll = 1 - pshl

dicty = {'pbhh': pbhh, 'pbdh': pbdh, 'pbll': pbll, 'pbdl': pbdl, 'pshh': pshh, 'pslh': pslh, 'pshl': pshl, 'psll': psll, 'e': e}
dfside1 = pd.DataFrame(dicty)
dfside1['muh'] = dfside1['pshh'] / (dfside1['pshh'] + dfside1['pshl'])
dfside1['mul'] = (1 - dfside1['pshh']) / (2 - dfside1['pshh'] - dfside1['pshl'])

# Just for graphing
dfside1['e'] = 1 - dfside1['e']
dfside1['pshl'] = dfside1['pshl'] - 0.01
dfside1['mul'] = dfside1['mul'] - 0.01

dfmain1.to_excel('../output/Trembling Hand/th_main_1s.xlsx', index=False)
dfside1.to_excel('../output/Trembling Hand/th_side_1s.xlsx', index=False)

output_file = '../output/Trembling Hand/THprobsmain_n1.data'
dfmain1.to_csv(output_file, sep=',', index=False)
print(f'Data written to {output_file}')

output_file = '../output/Trembling Hand/THprobsside_n1.data'
dfside1.to_csv(output_file, sep=',', index=False)
print(f'Data written to {output_file}')

tex_code = r"""
\begin{figure}[htbp]\flushleft
    
\begin{subfigure}[b]{0.7\textwidth}
\begin{tikzpicture}
\begin{axis}[ylabel={Seller Choice Probabilities}, width=\textwidth, height=0.3\textheight, no markers, legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, legend cell align={left}, ultra thick, xmin=-0.01, xticklabels={}, ymin=0, ymax=1]
\addplot [color=blue, solid] table [x=e, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addlegendentry{$\mathbb{P}(p_H|v_H)$}
\addplot [color=orange, solid] table [x=e, y=pshl, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addlegendentry{$\mathbb{P}(p_H|v_L)$}
\addplot [color=blue, solid] table [x=e, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\addplot [color=orange, solid] table [x=e, y=pshl, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\end{axis}
\end{tikzpicture}
\end{subfigure}

\begin{subfigure}[b]{0.7\textwidth}
\begin{tikzpicture}
\begin{axis}[ylabel={Buyer Choice Probabilities}, width=\textwidth, height=0.3\textheight, no markers, legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, legend cell align={left}, ultra thick, xmin=-0.01, xmax=1.01, xticklabels={}, ymin=0, ymax=1]
\addplot [color=blue, solid] table [x=e, y=pbhh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addlegendentry{$\mathbb{P}(\text{buy}|p_H, \ p_H)$}
\addplot [color=orange, solid] table [x=e, y=pbll, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addlegendentry{$\mathbb{P}(\text{buy}|p_L, \ p_L)$}
\addplot [color=blue, solid] table [x=e, y=pbhh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\addplot [color=orange, solid] table [x=e, y=pbll, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\end{axis}
\end{tikzpicture}
\end{subfigure}

\begin{subfigure}[b]{0.7\textwidth}
\begin{tikzpicture}
\begin{axis}[ylabel={Buyer Beliefs}, xlabel={Precision ($1 - \epsilon$)}, width=\textwidth, height=0.3\textheight, no markers, legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, legend cell align={left}, ultra thick, xmin=-0.01, xmax=1.01, ymin=0, ymax=1]
\addplot [color=blue, solid] table [x=e, y=muh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addlegendentry{$\mathbb{P}(v_H|p_H)$}
\addplot [color=orange, solid] table [x=e, y=mul, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addlegendentry{$\mathbb{P}(v_H|p_L)$}
\addplot [color=blue, solid] table [x=e, y=muh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\addplot [color=orange, solid] table [x=e, y=mul, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\end{axis}
\end{tikzpicture}
\end{subfigure}

\caption{Trembling-hand correspondence for $n=1$}
\label{THprobs_n1}
%\begin{minipage}{0.7\textwidth}
%\footnotesize
%\textit{Notes:} This figure is based on the actual parameter values used in the experiment. Because firms are symmetric, the average price is simply $x p_H + (1-x) p_L$ where $x$ is the unconditional probability of an individual firm setting the high price.
%\end{minipage}
\end{figure}
"""

with open("../output/Trembling Hand/THprobs_n1.tex", "w") as file:
    file.write(tex_code)
print('Created THprobs_n1.tex')

#--------------------n = 1: seller strategy space--------------------#

eqa = np.load('../output/Theory Section/eqa.npz')
loc_n1_lmix_eq = (eqa['lmix_pi_1s'][6], eqa['lmix_pi_1s'][4])
loc_n1_pool_eq = (eqa['pool_pi_1s'][6], eqa['pool_pi_1s'][4])

tex_code = r"""
\begin{figure}[htbp]
\begin{tikzpicture}
\begin{axis}[ylabel={$\mathbb{P}(p_H|v_H)$}, xlabel={$\mathbb{P}(p_H|v_L)$}, no markers, ultra thick, xmin=0, xmax=1, ymin=0, ymax=1]
\addplot [color=blue, solid] table [x=pshl, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addplot [color=blue, solid] table [x=pshl, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\addplot [color=blue, only marks, mark=*, mark size=3] coordinates {<<loc_n1_lmix_eq>>};
\addplot [color=blue, only marks, mark=*, mark size=3] coordinates {<<loc_n1_pool_eq>>};
\end{axis}
\end{tikzpicture}
\caption{Trembling-Hand Seller Strategies for $n=1$}
\label{THsellerstrat_n1}
%\begin{minipage}{0.8\textwidth}
%\footnotesize
%\textit{Notes:} This figure is based on the actual parameter values used in the experiment. Because firms are symmetric, the average price is simply $x p_H + (1-x) p_L$ where $x$ is the unconditional probability of an individual firm setting the high price.
%\end{minipage}
\end{figure}
"""

replacements = {"<<loc_n1_lmix_eq>>": str(loc_n1_lmix_eq),
                "<<loc_n1_pool_eq>>": str(loc_n1_pool_eq)}

for placeholder, value in replacements.items():
    tex_code = tex_code.replace(placeholder, value)

with open("../output/Trembling Hand/THsellerstrat_n1.tex", "w") as file:
    file.write(tex_code)
print('Created THsellerstrat_n1.tex')
    
#--------------------n = 2: choice probs on e--------------------#

def poolpl(e):
    shh = e / 2
    shl = e / 2
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def poolph(e):
    shh = (2 - e) / 2
    shl = (2 - e) / 2
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def separatingB(bhb):
    e = 0.2
    shh = 9 / 10
    shl = 1 / 10
    bhh = 9 / 10
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def separatingC(e):
    shh = (2 - e) / 2
    shl = e / 2
    bhh = (2 - e) / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixA(e):
    shh = (2 - e) / 2
    shl = (-36 + 56 * e - 3 * e**2) / (12 - 6 * e)
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixB(e):
    shh = (2 - e) / 2
    shl = (2 - e) / 3
    bhh = (44 - 44 * e - 5 * e**2) / (40 - 20 * e)
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixC(e):
    shh = (2 - e) / 2
    shl = (-12 + 20 * e + 9 * e**2) / (-12 + 18 * e)
    bhh = (2 - e) / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixD(e):
    shh = (2 - e) / 2
    shl = (5 + 4 * e - (9 + 80 * e)**0.5) / 8
    bhh = (2 - e) / 2
    bhb = (12 + 4 * e - 5 * e**2 + 2 * (5 * e - 6) * shl) / (72 + 12 * e - 24 * shl)
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixB(e):
    shh = (3 - 4 * e + (9 + 80 * e)**0.5) / 8
    shl = e / 2
    bhh = (2 - e) / 2
    bhb = (15 - 6 * e - (3 - 2 * e) * (9 + 80 * e)**0.5) / (126 - 6 * (9 + 80 * e)**0.5)
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixC(e):
    shh = (3 - 9 * e + 2 * e**2) / (3 - 4 * e)
    shl = e / 2
    bhh = (2 - e) / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixD(e):
    shh = 3 * e / 4
    shl = e / 2
    bhh = (48 - 90 * e + 35 * e**2) / (90 * e)
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixE(e):
    shh = (-12 + 27 * e + e**2) / (6 - 2 * e)
    shl = e / 2
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

theqa = [poolpl, poolph, separatingC, lowmixA, lowmixB, lowmixC, lowmixD, highmixB, highmixC, highmixD, highmixE]

# Cutoffs
e1 = 0.0909334
e2 = 0.2
e3 = (45 - 1065**0.5) / 40
e4 = 0.4
e5 = 6/13
e6 = 42**0.5 - 6
e7 = (2505**0.5 - 45) / 10
e8 = (32 - 804**0.5) / 5
e9 = (17 - 217**0.5) / 3
bhb1 = 1/10
bhb2 = 29/180

cutoffs_by_eqa = [[0,e6],[e9,1],[e2,e5],[e8,e9],[e4,e8],[e4,e5],[0,e2],[0,e1],[e1,e3],[e3,e7],[e6,e7]]

samples = 20
for i in range(len(theqa)):
    e = np.linspace(cutoffs_by_eqa[i][0], cutoffs_by_eqa[i][1], samples)
    pi = theqa[i](e)
    pshh = pi[7]
    pshl = pi[9]
    pbhh = pi[0]
    pbll = pi[2]
    pbhb = pi[4]
    pblb = pi[5]
    muh = pshh/(pshh+pshl)
    mul = (1-pshh)/(2-pshh-pshl)
    df = pd.DataFrame({'e': e,
                       'pshh': pshh,
                       'pshl': pshl,
                       'pbhh': pbhh,
                       'pbll': pbll,
                       'pbhb': pbhb,
                       'pblb': pblb,
                       'muh': muh,
                       'mul': mul})
    # For graphing
    df['e'] = 1 - df['e']
    df['pshl'] = df['pshl'] - 0.01
    df['pbhh'] = df['pbhh'] - 0.01
    df['pbhb'] = df['pbhb'] - 0.01
    df['mul'] = df['mul'] - 0.01
    output_file = '../output/Trembling Hand/THprobs_n2_' + str(i) + '.data'
    df.to_csv(output_file, sep=',', index=False)
    print(f'Data written to {output_file}')

# Need to do sepB separately
pbhb = np.linspace(bhb1,bhb2,samples)
pi = separatingB(pbhb)
pshh = pi[7]
pshl = pi[9]
pbhh = pi[0]
pbll = pi[2]
pbhb = pi[4]
pblb = pi[5]
muh = pshh/(pshh+pshl)
mul = (1-pshh)/(2-pshh-pshl)
e = np.array([e2 for x in range(samples)])
df = pd.DataFrame({'e': e,
                   'pshh': pshh,
                   'pshl': pshl,
                   'pbhh': pbhh,
                   'pbll': pbll,
                   'pbhb': pbhb,
                   'pblb': pblb,
                   'muh': muh,
                   'mul': mul})
# For graphing
df['e'] = 1 - df['e']
df['pshl'] = df['pshl'] - 0.01
df['pbhh'] = df['pbhh'] - 0.01
df['pbhb'] = df['pbhb'] - 0.01
df['mul'] = df['mul'] - 0.01
output_file = '../output/Trembling Hand/THprobs_n2_' + str(len(theqa)) + '.data'
df.to_csv(output_file, sep=',', index=False)
print(f'Data written to {output_file}')

tex_code = r"""
\begin{figure}[htbp]\flushleft
    
\begin{subfigure}[b]{0.7\textwidth}
\begin{tikzpicture}
\begin{axis}[ylabel={Seller Choice Probabilities}, width=\textwidth, height=0.3\textheight, no markers, legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, legend cell align={left}, ultra thick, xmin=-0.01, xmax=1.01, xticklabels={}, ymin=0, ymax=1,
legend entries={$\mathbb{P}(p_H|v_H)$,$\mathbb{P}(p_H|v_L)$}]
\addlegendimage{no markers, blue, solid}
\addlegendimage{no markers, orange, solid}
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=blue, solid] table [x=e, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=orange, solid] table [x=e, y=pshl, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

tex_code += r"""
\end{axis}
\end{tikzpicture}
\end{subfigure}

\begin{subfigure}[b]{0.7\textwidth}
\begin{tikzpicture}
\begin{axis}[   ylabel={Buyer Choice Probabilities}, 
                width=\textwidth, 
                height=0.3\textheight, 
                no markers, 
                legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, 
                legend cell align={left}, 
                ultra thick, 
                xmin=-0.01, xmax=1.01, xticklabels={}, 
                ymin=0, ymax=1,
                legend entries={$\mathbb{P}(\text{buy}|{p_H, \ p_H})$,
                                $\mathbb{P}(\text{buy}|{p_L, \ p_L})$,
                                $\mathbb{P}({\text{buy} \ p_H}|{p_H, \ p_L})$,
                                $\mathbb{P}({\text{buy} \ p_L}|{p_H, \ p_L})$}
                ]
\addlegendimage{no markers, blue, solid}
\addlegendimage{no markers, orange, solid}
\addlegendimage{no markers, blue, dashed}
\addlegendimage{no markers, orange, dashed}
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=blue, solid] table [x=e, y=pbhh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=orange, solid] table [x=e, y=pbll, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=blue, dashed] table [x=e, y=pbhb, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=orange, dashed] table [x=e, y=pblb, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

tex_code += r"""
\end{axis}
\end{tikzpicture}
\end{subfigure}

\begin{subfigure}[b]{0.7\textwidth}
\begin{tikzpicture}
\begin{axis}[ylabel={Buyer Beliefs}, xlabel={Precision ($1 - \epsilon$)}, width=\textwidth, height=0.3\textheight, no markers, legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, legend cell align={left}, ultra thick, xmin=-0.01, xmax=1.01, ymin=0, ymax=1,
legend entries={$\mathbb{P}(v_H|p_H)$,$\mathbb{P}(v_H|p_L)$}]
\addlegendimage{no markers, blue, solid}
\addlegendimage{no markers, orange, solid}
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=blue, solid] table [x=e, y=muh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

for i in range(len(theqa)+1):
    tex_code += r"""
\addplot [color=orange, solid] table [x=e, y=mul, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
"""

tex_code += r"""
\end{axis}
\end{tikzpicture}
\end{subfigure}

\caption{Trembling-hand correspondence for $n=2$}
\label{THprobs_n2}
%\begin{minipage}{0.7\textwidth}
%\footnotesize
%\textit{Notes:} This figure is based on the actual parameter values used in the experiment. Because firms are symmetric, the average price is simply $x p_H + (1-x) p_L$ where $x$ is the unconditional probability of an individual firm setting the high price.
%\end{minipage}
\end{figure}
"""

with open("../output/Trembling Hand/THprobs_n2.tex", "w") as file:
    file.write(tex_code)
print('Created THprobs_n2.tex')

#--------------------n = 2: seller strategy space--------------------#

loc_n2_lmix_eq = (eqa['lmix_pi_2s'][9], eqa['lmix_pi_2s'][7])
loc_n2_hmix_eq = (eqa['hmix_pi_2s'][9], eqa['hmix_pi_2s'][7])
loc_n2_pool_eq = (eqa['pool_pi_2s'][9], eqa['pool_pi_2s'][7])

tex_code = r"""
\begin{figure}[htbp]
\begin{tikzpicture}
\begin{axis}[ylabel={$\mathbb{P}(p_H|v_H)$}, xlabel={$\mathbb{P}(p_H|v_L)$}, no markers, ultra thick, xmin=0, xmax=1, ymin=0, ymax=1]
"""

for i in range(len(theqa)+1):
    tex_code += r"""
    \addplot [color=blue, solid] table [x=pshl, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
    """

tex_code += r"""
\addplot [color=blue, only marks, mark=*, mark size=3] coordinates {<<loc_n2_lmix_eq>>};
\addplot [color=blue, only marks, mark=*, mark size=3] coordinates {<<loc_n2_hmix_eq>>};
\addplot [color=blue, only marks, mark=*, mark size=3] coordinates {<<loc_n2_pool_eq>>};
\end{axis}
\end{tikzpicture}
\caption{Trembling-Hand Seller Strategies for $n=2$}
\label{THsellerstrat_n2}
%\begin{minipage}{0.8\textwidth}
%\footnotesize
%\textit{Notes:} This figure is based on the actual parameter values used in the experiment. Because firms are symmetric, the average price is simply $x p_H + (1-x) p_L$ where $x$ is the unconditional probability of an individual firm setting the high price.
%\end{minipage}
\end{figure}
"""

replacements = {"<<loc_n2_lmix_eq>>": str(loc_n2_lmix_eq),
                "<<loc_n2_hmix_eq>>": str(loc_n2_hmix_eq),
                "<<loc_n2_pool_eq>>": str(loc_n2_pool_eq)}

for placeholder, value in replacements.items():
    tex_code = tex_code.replace(placeholder, value)

with open("../output/Trembling Hand/THsellerstrat_n2.tex", "w") as file:
    file.write(tex_code)
print('Created THsellerstrat_n2.tex')


Running Trembling Hand
Data written to THprobsmain_n1.data
Data written to THprobsside_n1.data
Created THprobs_n1.tex
Created THsellerstrat_n1.tex
Data written to THprobs_n2_0.data
Data written to THprobs_n2_1.data
Data written to THprobs_n2_2.data
Data written to THprobs_n2_3.data
Data written to THprobs_n2_4.data
Data written to THprobs_n2_5.data
Data written to THprobs_n2_6.data
Data written to THprobs_n2_7.data
Data written to THprobs_n2_8.data
Data written to THprobs_n2_9.data
Data written to THprobs_n2_10.data
Data written to THprobs_n2_11.data
Created THprobs_n2.tex
Created THsellerstrat_n2.tex


<ipython-input-4-5459ed0d76e0>:313: RuntimeWarning: invalid value encountered in true_divide
  muh = pshh/(pshh+pshl)
<ipython-input-4-5459ed0d76e0>:203: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])


In [5]:
#--------------------Finite Mixture Model--------------------#

from scipy.optimize import minimize
from sklearn.utils import resample

#--------------------n = 1 MLE--------------------#

print('MLE for n = 1...')
# cutoffs:
e1 = 2 * kh / (1 + kh)
e2 = 2 * kl / (1 + kl)

def th_mle_1s(data):
    ResultList = []
    
    #bounds on e from e2 to 1
    def loglikelihoodn1_above_e2(e, pis=False):
        pi = np.array([e/2, 1 - e/2, 1 - e/2, e/2, 1 - e/2, e/2, 1 - e/2, e/2])
        if pis == True:
            return pi
        logsum = (np.dot(data, np.log(pi))).sum()
        return -logsum
    bounds = [(e2, 1)]
    result = minimize(loglikelihoodn1_above_e2, np.array([5/6]), bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglikelihoodn1_above_e2, 5])

    #bounds on e from e1 to e2
    def loglikelihoodn1_e1_to_e2(e, pis=False):
        pi = np.array([1/2 - e/4, 1/2 + e/4, 1 - e/2, e/2, 1 - e/2, e/2, 2/3 - e/3, 1/3 + e/3])
        if pis == True:
            return pi
        logsum = (np.dot(data, np.log(pi))).sum()
        return -logsum
    bounds = [(e1, e2)]
    result = minimize(loglikelihoodn1_e1_to_e2, np.array([7/12]), bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglikelihoodn1_e1_to_e2, 3])

    #bounds on e from 0 to e1, on each q from 0 to 1, and constraint that qs must sum to 1
    def loglikelihoodn1_below_e1(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi_lowmix = np.array([1/2 - e/4, 1/2 + e/4, 1 - e/2, e/2, 1 - e/2, e/2, 2/3 - e/3, 1/3 + e/3])
        pi_pool1  = np.array([e/2, 1 - e/2, 1 - e/2, e/2, e/2, 1 - e/2, e/2, 1 - e/2])
        pi_pool2  = np.array([1/3 - e/6, 2/3 + e/6, 1 - e/2, e/2, 3*e/4, 1 - 3*e/4, e/2, 1 - e/2])
        pi = np.array([pi_lowmix, pi_pool1, pi_pool2]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(0, e1), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([1/4, 1/3, 1/3, 1/3])
    result = minimize(loglikelihoodn1_below_e1, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglikelihoodn1_below_e1, 1])

    #bounds on x from 4/9 to 2/3
    def loglikelihoodn1_at_e2(x, pis=False):
        pi = np.array([1/3, 2/3, 2/3, 1/3, 2/3, 1/3, x[0], 1-x[0]])
        if pis == True:
            return pi
        logsum = (np.dot(data, np.log(pi))).sum()
        return -logsum
    bounds = [(4/9, 2/3)]
    result = minimize(loglikelihoodn1_at_e2, np.array([5/9]), bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglikelihoodn1_at_e2, 4])

    #bounds on x from 1/4 to 3/8, on q1, q2 between 0 and 1, and q1 + q2 = 1
    def loglikelihoodn1_at_e1(params, pis=False):
        x = params[0]
        q = params[1:].T
        pi_lowmix = np.array([3/8, 5/8, 3/4, 1/4, 3/4, 1/4, 1/2, 1/2])
        pi_pool   = np.array([1/4, 3/4, 3/4, 1/4, x, 1-x, 1/4, 3/4])
        pi = np.array([pi_lowmix, pi_pool]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] - 1}
    bounds = [(1/4, 3/8), (0, 1), (0, 1)]
    params0 = np.array([5/16, 1/2, 1/2])
    result = minimize(loglikelihoodn1_at_e1, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglikelihoodn1_at_e1, 2])

    for res in ResultList:
        if res[0] != True:
            print('Error: failed to minimize likelihood!')

    best_result_n1 = min(ResultList, key=lambda x: x[1])
    best_params_n1 = best_result_n1[2]
    best_func_n1 = best_result_n1[3]
    best_pis_n1 = best_func_n1(best_params_n1, pis=True)
    
    if best_result_n1[4] == 1:
        e_best = best_params_n1[0]
        q1_best = best_params_n1[1]
        q2_best = best_params_n1[2]
    elif best_result_n1[4] == 2:
        e_best = e1
        q1_best = best_params_n1[1]
        q2_best = best_params_n1[2]
    elif best_result_n1[4] == 3:
        e_best = best_params_n1[0]
        q1_best = 1
        q2_best = 0
    elif best_result_n1[4] == 4:
        e_best = e2
        q1_best = 1
        q2_best = 0
    elif best_result_n1[4] == 5:
        e_best = best_params_n1[0]
        q1_best = 1
        q2_best = 0
        
    return [e_best, q1_best, q2_best, best_pis_n1]

# Bootstrapping for standard errors
n_bootstrap = 1000
n_data_points = len(data_1s)

e_1s = []
q1_1s = []
q2_1s = []
for i in range(n_bootstrap):
    resampled_data_1s = resample(data_1s, replace=True, n_samples=n_data_points)
    bootstrap_sample_1s = np.mean(resampled_data_1s, axis=0)
    result = th_mle_1s(bootstrap_sample_1s)
    e_1s.append(result[0])
    q1_1s.append(result[1])
    q2_1s.append(result[2])

best_1s = th_mle_1s(data_1s)
best_params_1s = best_1s[:3]
best_pis_1s = best_1s[3]
se_1s = [np.var(np.array(x))**0.5 for x in [e_1s, q1_1s, q2_1s]]

#print('n = 1 trembling hand estimates: ', best_params_1s)
#print('n = 1 standard errors: ', se_1s)
#print('n = 1 choice probabilities: ', best_pis_1s)

#--------------------n = 2 MLE--------------------#

print('MLE for n = 2...')
# Choice probability order is:
# bhh, bdh, bll, bdl, bhb, blb, bdb, shh, slh, shl, sll

def poolpl(e):
    shh = e / 2
    shl = e / 2
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def poolph(e):
    shh = (2 - e) / 2
    shl = (2 - e) / 2
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def separatingB(bhb):
    e = 0.2
    shh = 9 / 10
    shl = 1 / 10
    bhh = 9 / 10
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def separatingC(e):
    shh = (2 - e) / 2
    shl = e / 2
    bhh = (2 - e) / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixA(e):
    shh = (2 - e) / 2
    shl = (-36 + 56 * e - 3 * e**2) / (12 - 6 * e)
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixB(e):
    shh = (2 - e) / 2
    shl = (2 - e) / 3
    bhh = (44 - 44 * e - 5 * e**2) / (40 - 20 * e)
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixC(e):
    shh = (2 - e) / 2
    shl = (-12 + 20 * e + 9 * e**2) / (-12 + 18 * e)
    bhh = (2 - e) / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def lowmixD(e):
    shh = (2 - e) / 2
    shl = (5 + 4 * e - (9 + 80 * e)**0.5) / 8
    bhh = (2 - e) / 2
    bhb = (12 + 4 * e - 5 * e**2 + 2 * (5 * e - 6) * shl) / (72 + 12 * e - 24 * shl)
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixB(e):
    shh = (3 - 4 * e + (9 + 80 * e)**0.5) / 8
    shl = e / 2
    bhh = (2 - e) / 2
    bhb = (15 - 6 * e - (3 - 2 * e) * (9 + 80 * e)**0.5) / (126 - 6 * (9 + 80 * e)**0.5)
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixC(e):
    shh = (3 - 9 * e + 2 * e**2) / (3 - 4 * e)
    shl = e / 2
    bhh = (2 - e) / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixD(e):
    shh = 3 * e / 4
    shl = e / 2
    bhh = (48 - 90 * e + 35 * e**2) / (90 * e)
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

def highmixE(e):
    shh = (-12 + 27 * e + e**2) / (6 - 2 * e)
    shl = e / 2
    bhh = e / 2
    bhb = e / 3
    bll = (2 - e) / 2
    bdb = e / 3
    return np.array([bhh, 1 - bhh, bll, 1 - bll, bhb, 1 - bhb - bdb, bdb, shh, 1 - shh, shl, 1 - shl])

# Cutoffs
e1 = 0.0909334
e2 = 0.2
e3 = (45 - 1065**0.5) / 40
e4 = 0.4
e5 = 6/13
e6 = 42**0.5 - 6
e7 = (2505**0.5 - 45) / 10
e8 = (32 - 804**0.5) / 5
e9 = (17 - 217**0.5) / 3

# Negative Log Likelihood
def th_mle_2s(data):
    ResultList = []
    def loglike_0_to_e1(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([lowmixD(e), highmixB(e), poolpl(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(0, e1), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.04, 1/3, 1/3, 1/3])
    result = minimize(loglike_0_to_e1, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_0_to_e1, 1])

    def loglike_e1_to_e2(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([lowmixD(e), highmixC(e), poolpl(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(e1, e2), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.15, 1/3, 1/3, 1/3])
    result = minimize(loglike_e1_to_e2, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e1_to_e2, 2])

    def loglike_e2(params, pis=False):
        bhb = params[0]
        q = params[1:].T
        pi = np.array([separatingB(bhb), highmixC(e2), poolpl(e2)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(1/15, 29/180), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([1/10, 1/3, 1/3, 1/3])
    result = minimize(loglike_e2, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e2, 3])

    def loglike_e2_to_e3(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([separatingC(e), highmixC(e), poolpl(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(e2, e3), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.25, 1/3, 1/3, 1/3])
    result = minimize(loglike_e2_to_e3, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e2_to_e3, 4])

    def loglike_e3_to_e4(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([separatingC(e), highmixD(e), poolpl(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(e3, e4), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.35, 1/3, 1/3, 1/3])
    result = minimize(loglike_e3_to_e4, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e3_to_e4, 5])

    def loglike_e4_to_e5(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([separatingC(e), lowmixC(e), lowmixB(e), highmixD(e), poolpl(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] +x[4] + x[5] - 1}
    bounds = [(e4, e5), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.42, 1/5, 1/5, 1/5, 1/5, 1/5])
    result = minimize(loglike_e4_to_e5, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e4_to_e5, 6])

    def loglike_e5_to_e6(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([lowmixB(e), highmixD(e), poolpl(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(e5, e6), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.475, 1/3, 1/3, 1/3])
    result = minimize(loglike_e5_to_e6, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e5_to_e6, 7])

    def loglike_e6_to_e7(params, pis=False):
        e = params[0]
        q = params[1:].T
        pi = np.array([lowmixB(e), highmixD(e), highmixE(e)]).T
        if pis == True:
            return pi
        logsum_ij = np.matmul(data, np.log(pi))
        logsum_i = np.matmul(np.exp(logsum_ij), q)
        logsum = (np.log(logsum_i)).sum()
        return -logsum
    constraints = {'type': 'eq', 'fun': lambda x: x[1] + x[2] + x[3] - 1}
    bounds = [(e6, e7), (0, 1), (0, 1), (0, 1)]
    params0 = np.array([0.49, 1/3, 1/3, 1/3])
    result = minimize(loglike_e6_to_e7, params0, constraints=constraints, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e6_to_e7, 8])

    def loglike_e7_to_e8(e, pis=False):
        pi = lowmixB(e)
        if pis == True:
            return pi
        logsum_i = np.dot(data, np.log(pi))
        logsum = logsum_i.sum()
        return -logsum
    bounds = [(e7, e8)]
    params0 = np.array([0.6])
    result = minimize(loglike_e7_to_e8, params0, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e7_to_e8, 9])

    def loglike_e8_to_e9(e, pis=False):
        pi = lowmixA(e)
        if pis == True:
            return pi
        logsum_i = np.dot(data, np.log(pi))
        logsum = logsum_i.sum()
        return -logsum
    bounds = [(e8, e9)]
    params0 = np.array([0.74])
    result = minimize(loglike_e8_to_e9, params0, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e8_to_e9, 10])

    def loglike_e9_to_1(e, pis=False):
        pi = poolph(e)
        if pis == True:
            return pi
        logsum_i = np.dot(data, np.log(pi))
        logsum = logsum_i.sum()
        return -logsum
    bounds = [(e9, 1)]
    params0 = np.array([0.88])
    result = minimize(loglike_e9_to_1, params0, bounds=bounds)
    ResultList.append([result.success, result.fun, result.x, loglike_e9_to_1, 11])

    for res in ResultList:
        if res[0] != True:
            print('Error: failed to minimize likelihood!')

    best_result_2s = min(ResultList, key=lambda x: x[1])
    best_params_2s = best_result_2s[2]
    best_func_2s = best_result_2s[3]
    best_pis_2s = best_func_2s(best_params_2s, pis=True)
    
    if best_result_2s[4] == 1:
        e_best = best_params_2s[0]
        q1_best = best_params_2s[1]
        q2_best = 0
        q3_best = 0
        q4_best = best_params_2s[2]
        q5_best = best_params_2s[3]
    elif best_result_2s[4] == 2:
        e_best = best_params_2s[0]
        q1_best = best_params_2s[1]
        q2_best = 0
        q3_best = 0
        q4_best = best_params_2s[2]
        q5_best = best_params_2s[3]
    elif best_result_2s[4] == 3:
        e_best = e2
        q1_best = best_params_2s[0]
        q2_best = 0
        q3_best = 0
        q4_best = best_params_2s[1]
        q5_best = best_params_2s[2]
    elif best_result_2s[4] == 4:
        e_best = best_params_2s[0]
        q1_best = best_params_2s[1]
        q2_best = 0
        q3_best = 0
        q4_best = best_params_2s[2]
        q5_best = best_params_2s[3]
    elif best_result_2s[4] == 5:
        e_best = best_params_2s[0]
        q1_best = best_params_2s[1]
        q2_best = 0
        q3_best = 0
        q4_best = best_params_2s[2]
        q5_best = best_params_2s[3]
    elif best_result_2s[4] == 6:
        e_best = best_params_2s[0]
        q1_best = best_params_2s[1]
        q2_best = best_params_2s[2]
        q3_best = best_params_2s[3]
        q4_best = best_params_2s[4]
        q5_best = best_params_2s[5]
    elif best_result_2s[4] == 7:
        e_best = best_params_2s[0]
        q1_best = 0
        q2_best = 0
        q3_best = best_params_2s[1]
        q4_best = best_params_2s[2]
        q5_best = best_params_2s[3]
    elif best_result_2s[4] == 8:
        e_best = best_params_2s[0]
        q1_best = 0
        q2_best = 0
        q3_best = best_params_2s[1]
        q4_best = best_params_2s[2]
        q5_best = best_params_2s[3]
    elif best_result_2s[4] == 9:
        e_best = best_params_2s[0]
        q1_best = 0
        q2_best = 0
        q3_best = 1
        q4_best = 0
        q5_best = 0
    elif best_result_2s[4] == 10:
        e_best = best_params_2s[0]
        q1_best = 0
        q2_best = 0
        q3_best = 1
        q4_best = 0
        q5_best = 0
    elif best_result_2s[4] == 11:
        e_best = best_params_2s[0]
        q1_best = 0
        q2_best = 0
        q3_best = 1
        q4_best = 0
        q5_best = 0
        
    return [e_best, q1_best, q2_best, q3_best, q4_best, q5_best, best_pis_2s]

# Bootstrapping for standard errors
n_bootstrap = 1000
n_data_points = len(data_2s)

e_2s = []
q1_2s = []
q2_2s = []
q3_2s = []
q4_2s = []
q5_2s = []
for i in range(n_bootstrap):
    resampled_data_2s = resample(data_2s, replace=True, n_samples=n_data_points)
    bootstrap_sample_2s = np.mean(resampled_data_2s, axis=0)
    result = th_mle_2s(bootstrap_sample_2s)
    e_2s.append(result[0])
    q1_2s.append(result[1])
    q2_2s.append(result[2])
    q3_2s.append(result[3])
    q4_2s.append(result[4])
    q5_2s.append(result[5])

best_2s = th_mle_2s(data_2s)
best_params_2s = best_2s[:6]
best_pis_2s = best_2s[6]
se_2s = [np.var(np.array(x))**0.5 for x in [e_2s, q1_2s, q2_2s, q3_2s, q4_2s, q5_2s]]

#print('n = 2 trembling hand estimates: ', best_params_2s)
#print('n = 2 standard errors: ', se_2s)
#print('n = 2 choice probabilities: ', best_pis_2s)

#--------------------TH MLE graph--------------------#

loc_n1_lmix_eq = (eqa['lmix_pi_1s'][6], eqa['lmix_pi_1s'][4])
loc_n1_pool_eq = (eqa['pool_pi_1s'][6], eqa['pool_pi_1s'][4])
loc_n2_lmix_eq = (eqa['lmix_pi_2s'][9], eqa['lmix_pi_2s'][7])
loc_n2_hmix_eq = (eqa['hmix_pi_2s'][9], eqa['hmix_pi_2s'][7])
loc_n2_pool_eq = (eqa['pool_pi_2s'][9], eqa['pool_pi_2s'][7])
bestfitTH_n1 = (best_pis_1s[6][0], best_pis_1s[4][0])
bestfitTH_n2 = (best_pis_2s[9][0], best_pis_2s[7][0])

tex_code = r"""
\begin{figure}[htbp]\flushleft

\begin{subfigure}[b]{0.45\textwidth}
\begin{tikzpicture}[scale=0.85]
\begin{axis}[ylabel={$\mathbb{P}(p_H|v_H)$}, xlabel={$\mathbb{P}(p_H|v_L)$}, ultra thick, xmin=0, xmax=1, ymin=0, ymax=1]
\addplot[no markers, color=blue, solid] table [x=pshl, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsmain_n1.data};
\addplot[no markers, color=blue, solid] table [x=pshl, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobsside_n1.data};
\addplot[no markers, color=blue, only marks, mark=*, mark size=2] coordinates {<<loc_n1_lmix_eq>>};
\addplot[no markers, color=blue, only marks, mark=*, mark size=2] coordinates {<<loc_n1_pool_eq>>};
\addplot[only marks, mark=*, mark options={color=black, fill=black}] table[x=pshl_1s, y=pshh_1s, col sep=comma] {../output/Results Section/sellerstrat_bysession_first.data}; 
\node[star,star points=5,star point ratio=2.5,scale=0.7,draw] at <<bestfitTH_n1>> {} ;
\end{axis}
\end{tikzpicture}
\caption{$n = 1$}
\end{subfigure}
\hspace{0.01\textwidth}
\begin{subfigure}[b]{0.45\textwidth}
\begin{tikzpicture}[scale=0.85]
\begin{axis}[ylabel={}, xlabel={$\mathbb{P}(p_H|v_L)$}, ytick={}, yticklabels={}, ultra thick, xmin=0, xmax=1, ymin=0, ymax=1, legend style={at={(1.1,0.5)}, anchor=west, legend columns=1}, legend cell align=left,
legend entries={Data,Best-fit THPE}]
\addlegendimage{color=black, only marks, mark=*, mark size=2}
\addlegendimage{mark=none, legend image code/.code={%
\node[star,star points=5,star point ratio=2.5,scale=0.5,draw] at (0.3cm,0) {};
}}"""

for i in range(len(theqa)+1):
    tex_code += r"""
    \addplot [color=blue, solid] table [x=pshl, y=pshh, col sep=comma, unbounded coords=jump] {../output/Trembling Hand/THprobs_n2_""" + str(i) + """.data};
    """

tex_code += r"""
\addplot[color=blue, only marks, mark=*, mark size=2, forget plot] coordinates {<<loc_n2_lmix_eq>>};
\addplot[color=blue, only marks, mark=*, mark size=2, forget plot] coordinates {<<loc_n2_hmix_eq>>};
\addplot[color=blue, only marks, mark=*, mark size=2, forget plot] coordinates {<<loc_n2_pool_eq>>};
\addplot[only marks, mark=*, mark options={color=black, fill=black}] table[x=pshl_2s, y=pshh_2s, col sep=comma, forget plot] {../output/Results Section/sellerstrat_bysession_first.data}; 
\node[star,star points=5,star point ratio=2.5,scale=0.7,draw] at <<bestfitTH_n2>> {};
\end{axis}
\end{tikzpicture}
\caption{$n = 2$}
\end{subfigure}

\caption{Trembling-Hand Seller Strategies}
\label{thsellerstratmle}
%\begin{minipage}{0.8\textwidth}
%\footnotesize
%\textit{Notes:} Notice this notable note denotes noteworthy notices.
%\end{minipage}
\end{figure}
"""

replacements = {"<<loc_n1_lmix_eq>>": str(loc_n1_lmix_eq),
                "<<loc_n1_pool_eq>>": str(loc_n1_pool_eq),
                "<<loc_n2_lmix_eq>>": str(loc_n2_lmix_eq),
                "<<loc_n2_hmix_eq>>": str(loc_n2_hmix_eq),
                "<<loc_n2_pool_eq>>": str(loc_n2_pool_eq),
                "<<bestfitTH_n1>>": str(bestfitTH_n1),
                "<<bestfitTH_n2>>": str(bestfitTH_n2)}

for placeholder, value in replacements.items():
    tex_code = tex_code.replace(placeholder, value)

with open("../output/Trembling Hand/thsellerstratmle.tex", "w") as file:
    file.write(tex_code)
print('Created thsellerstratmle.tex')
print('\n')


MLE for n = 1...
n = 1 trembling hand estimates:  [0.3748633451587299, 0.9999999999999996, 0.0]
n = 1 standard errors:  [0.035343740122398104, 3.324186464221916e-16, 1.2572507092943306e-16]
n = 1 choice probabilities:  [[0.40628416 0.18743167 0.27085611]
 [0.59371584 0.81256833 0.72914389]
 [0.81256833 0.81256833 0.81256833]
 [0.18743167 0.18743167 0.18743167]
 [0.81256833 0.18743167 0.28114751]
 [0.18743167 0.81256833 0.71885249]
 [0.54171222 0.18743167 0.18743167]
 [0.45828778 0.81256833 0.81256833]]
MLE for n = 2...
n = 2 trembling hand estimates:  [0.4607602363335778, 0.0, 0.0, 0.0, 1.0, 0.0]
n = 2 standard errors:  [0.10361360974458264, 5.952961539496553e-15, 5.780448524097015e-15, 0.45468230667134674, 0.45002404522424005, 0.10208683183393748]
n = 2 choice probabilities:  [[0.76961988 0.76961988 0.73624169 0.33669183 0.23038012]
 [0.23038012 0.23038012 0.26375831 0.66330817 0.76961988]
 [0.76961988 0.76961988 0.76961988 0.76961988 0.76961988]
 [0.23038012 0.23038012 0.23038012 0.2